const huntingPeriods = [
    {
        id: 1,
        key: 0,
        imgPath: "./images/auerwild.jpg",
        name: "Auerwild",
        paarbildung: "polygam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Raufußhühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfluechter",
        eier: "5-12",
        brutdauer: "26-28",
        balz: "Ende März-Mai",
        zeiten: ["Januar", "Mai", "Ende März-Mai"]
    },
    {
        id: 2,
        key: 1,
        imgPath: "./images/birkwild.jpg",
        name: "Birkwild",
        paarbildung: "polygam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Raufußhühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfluechter",
        eier: "6-10",
        brutdauer: "25-28",
        balz: "April-Juni",
        zeiten: ["Januar", "Mai", "April-Juni"]
    },
    {
        id: 3,
        key: 2,
        imgPath: "./images/alpenschneehuhn.jpg",
        name: "Alpenschneehuhn",
        paarbildung: "monogam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Raufußhühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfluechter",
        eier: "6-9",
        brutdauer: "24",
        balz: "April/Mai",
        zeiten: ["Januar", "Mai", "April/Mai"]
    },
    {
        id: 4,
        key: 3,
        imgPath: "./images/haselwild.jpg",
        name: "Haselwild",
        paarbildung: "monogam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Raufußhühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfluechter",
        eier: "6-9",
        brutdauer: "24",
        balz: "September/Oktober",
        zeiten: ["Januar", "Mai", "September/Oktober"]
    },
    {
        id: 5,
        key: 3,
        imgPath: "./images/rebhuhn.jpg",
        name: "Rebhuhn",
        paarbildung: "monogam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Feldhühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfolger",
        eier: "10-20",
        brutdauer: "21-24",
        balz: "Februar-März",
        zeiten: ["Januar", "Mai", "Februar-März"]
    },
    {
        id: 6,
        key: 5,
        imgPath: "./images/wachtel.jpg",
        name: "Wachtel",
        paarbildung: "monogam/polygam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Feldhühner",
        zugverhalten: "zugvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfolger",
        eier: "8-15",
        brutdauer: "17",
        balz: "Mai-Juni",
        zeiten: ["Januar", "Mai", "Mai-Juni"]
    },
    {
        id: 7,
        key: 6,
        imgPath: "./images/fasan.jpg",
        name: "Fasan",
        paarbildung: "polygam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Fasanen",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfolger",
        eier: "10-12",
        brutdauer: "24",
        balz: "März-April",
        zeiten: ["Januar", "Mai", "März-April"]
    },
    {
        id: 8,
        key: 7,
        imgPath: "./images/wildtruhthahn.jpg",
        name: "Wildtruthuhn",
        paarbildung: "polygam",
        nester: "bodenbrueter",
        ordnung: "Hühnervögel",
        unterfamilie: "Truthühner",
        zugverhalten: "standvogel",
        junge: "nestfluechter",
        kulturtyp: "kulturfolger",
        eier: "9-15",
        brutdauer: "28",
        balz: "März-April",
        zeiten: ["Januar", "Mai", "März-April"]
    }





];

export default huntingPeriods;
